name: Build 

jobs:
  os_maxtrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2022]
  build-osx:
    runs-on: macos-12 
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
  build-linux:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --features vendored --verbose
  build-windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
